[Config]
Dependencies=os

[Match]
Distribution=ubuntu
Release=resolute
Profiles=sysexts

[Output]
Format=sysext
Overlay=yes
ImageId=ext-devel

[Content]
Bootable=no
BaseTrees=%O/Elementary_%v_%a.raw
Packages=
    cmake
    meson
    sassc
    libxml2-dev
    libdbus-1-dev
    libadwaita-1-dev
    git
    build-essential
    ripgrep
    dnsutils
    podman-compose
    gcc
    gettext
    distrobox
    fastfetch
    binutils
    curl
    wget
    htop
    podman
    vim
    fzf
    gcr
    git
    just
    lshw
    ssh-askpass-gnome
    yq
    jq