[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes
ToolsTreeDistribution=debian
ToolsTreeRelease=forky

[Output]
Format=none
OutputDirectory=mkosi.output
ImageId=Elementary