[Match]
Profiles=sysupdate

[Output]
SplitArtifacts=uki,partitions
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImageFormat=%i_%v_%a
InitrdProfiles=
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
    dm-verity
KernelCommandLine=
    splash
    quiet
    root=dissect
    mount.usr=dissect
    rw
    audit=0
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:home=unprotected+absent:=ignore
    systemd.image_filter=usr=Elementary_*:usr-verity=Elementary_*:usr-verity-sig=Elementary_*:root=Elementary-*:home=Elementary-*
    systemd.debug-shell=ttyS0
    rd.systemd.debug-shell=ttyS0
    ipe.enforce=0

[Validation]
# just for now, please do enable secureboot
SecureBoot=no
SignExpectedPcr=no
