[Match]
Distribution=ubuntu

[Content]
Packages=
    appcenter
    pantheon-greeter
    elementary-artwork
    elementary-wallpapers
    fonts-inter
    fonts-elementary-core
    fonts-elementary-extra
    fonts-roboto-mono-elementary
    elementary-default-settings
    elementary-desktop
    elementary-minimal
    elementary-printer-test-page
    elementary-os-overlay
    elementary-icon-theme
    elementary-sdk
    elementary-standard
    io.elementary.session-settings
    io.elementary.initial-setup
    gnome-session-bin
    gnome-session-common
    desktop-base
    pantheon-shell
    pantheon
    io.elementary.settings-daemon
    io.elementary.portals
    pantheon-agent-polkit
    xwayland
    gala





