[Match]
Distribution=ubuntu

[Content]
Packages=
    io.elementary.settings
    io.elementary.settings.applications
    io.elementary.settings.bluetooth
    io.elementary.settings.datetime
    io.elementary.settings.desktop
    io.elementary.settings.display
    io.elementary.settings.keyboard
    io.elementary.settings.locale
    io.elementary.settings.mouse-touchpad
    io.elementary.settings.network
    io.elementary.settings.notifications
    io.elementary.settings.onlineaccounts
    io.elementary.settings.power
    io.elementary.settings.printers
    io.elementary.settings.screentime-limits
    io.elementary.settings.security-privacy
    io.elementary.settings.sound
    io.elementary.settings.system
    io.elementary.settings.useraccounts
    io.elementary.settings.wacom





