[Content]
RemoveFiles=
    /usr/bin/chsh
    /usr/bin/lchsh

VolatilePackages=
    systemd-container

RemovePackages=
    anacron

Packages=
    plymouth
    plymouth-theme-elementary
    pipewire-audio
    linux-image-generic
    linux-firmware
    libpam-systemd
    dbus-user-session
    systemd-resolved
    systemd-cryptsetup
    cryptsetup
    btrfs-progs
    x11-common
    iputils-ping
    fzf
    ubuntu-keyring
    flatpak
    locales-all
    glycin-loaders
    gnome-disk-utility
    gnome-keyring
    libpam-gnome-keyring
    micro
    vim
    ncurses-base
    network-manager
    systemd-homed
    sudo-rs
    xdg-desktop-portal-gtk
    xdg-user-dirs
    systemd-zram-generator
    systemd-repart