[Match]
Distribution=ubuntu

[Content]
Packages=
    contractor
    io.elementary.appcenter
    io.elementary.bluetooth-daemon
    io.elementary.code
    io.elementary.feedback
    io.elementary.monitor
    io.elementary.onboarding
    io.elementary.sideload
    io.elementary.terminal
    pantheon-files





