[Match]
Distribution=ubuntu

[Content]
Packages=
    io.elementary.dock
    io.elementary.notifications
    io.elementary.wingpanel
    io.elementary.shortcut-overlay
    io.elementary.panel.bluetooth
    io.elementary.panel.datetime
    io.elementary.panel.keyboard
    io.elementary.panel.network
    io.elementary.panel.nightlight
    io.elementary.panel.notifications
    io.elementary.panel.power
    io.elementary.quick-settings





