# SPDX-License-Identifier: LGPL-2.1-or-later

[UKIProfile]
Profile=
        ID=live
        TITLE=Live System

Cmdline=
        splash
        quiet
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=Elementary_*:usr-verity=Elementary_*:usr-verity-sig=Elementary_*:root=Elementary-*:home=Elementary-*
        systemd.debug-shell=ttyS0
        rd.systemd.debug-shell=ttyS0
        ipe.enforce=0

SignExpectedPcr=no