# SPDX-License-Identifier: LGPL-2.1-or-later

[UKIProfile]
Profile=
        ID=live
        TITLE=Live System

Cmdline=
        root=tmpfs
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:=ignore
        systemd.image_filter=usr=Elementary_*:usr-verity=Elementary_*:usr-verity-sig=Elementary_*:root=Elementary-*:home=Elementary-*
        ipe.enforce=0
        liveiso.live=1

SignExpectedPcr=no