[Match]
Distribution=ubuntu

[Content]
Packages=systemd-container

VolatilePackages=
    passwd
    login
    uidmap
    systemd-boot

InitrdVolatilePackages=
    systemd
    udev

InitrdPackages=
    linux-firmware
    cryptsetup
    cryptsetup-bin